name: stock-screener
channels:
  - defaults
dependencies:
  - matplotlib-base=3.3.1
  - pip=20.2.2
  - python=3.8.5
  - readline=8.0
  - seaborn=0.11.0
  - sqlite=3.33.0
  - pip:
    - numpy==1.19.2
    - pandas==1.1.2
    - pandas-datareader==0.9.0
    - requests==2.24.0
    - urllib3==1.25.10
    - yahoo-fin==0.8.6
    - yfinance==0.1.55

